version: '3'

services:
  # Databases
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: user_db,booking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-postgres-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-postgres-dbs.sh
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  # Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # Microservices
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=user_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PORT=3001

  event-service:
    build: ./event-service
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongo:mongo@mongodb:27017/event_db?authSource=admin
      - PORT=3002

  booking-service:
    build: ./booking-service
    ports:
      - "3003:3003"
    depends_on:
      - postgres
      - rabbitmq
      - event-service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=booking_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - EVENT_SERVICE_URL=http://event-service:3002
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - PORT=3003

  notification-service:
    build: ./notification-service
    ports:
      - "3004:3004"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - MONGO_URI=mongodb://mongo:mongo@mongodb:27017/notification_db?authSource=admin
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - PORT=3004

volumes:
  postgres_data:
  mongo_data: 